
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "chromium-ubuntu20.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux.zip"
    ],
)

http_file(
    name = "chromium-ubuntu22.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux.zip"
    ],
)

http_file(
    name = "chromium-ubuntu20.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-ubuntu22.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-debian11-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux.zip"
    ],
)

http_file(
    name = "chromium-debian11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-debian12-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux.zip"
    ],
)

http_file(
    name = "chromium-debian12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-mac10.13",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac10.14",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac10.15",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac11",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-mac12",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-mac13",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac13-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-mac14",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac.zip"
    ],
)

http_file(
    name = "chromium-mac14-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-win64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium/1112/chromium-win64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium/1112/chromium-win64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium/1112/chromium-win64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-ubuntu20.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-ubuntu22.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-ubuntu20.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-ubuntu22.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-debian11-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-debian11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-debian12-x64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-debian12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-linux-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac10.13",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac10.14",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac10.15",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac11",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac12",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac13",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac13-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac14",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-mac14-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-mac-arm64.zip"
    ],
)

http_file(
    name = "chromium-tip-of-tree-win64",
    urls = [
        "https://playwright.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-win64.zip",
        "https://playwright-akamai.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-win64.zip",
        "https://playwright-verizon.azureedge.net/builds/chromium-tip-of-tree/1205/chromium-tip-of-tree-win64.zip"
    ],
)

http_file(
    name = "firefox-ubuntu20.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-ubuntu-20.04.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-ubuntu-20.04.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-ubuntu-20.04.zip"
    ],
)

http_file(
    name = "firefox-ubuntu22.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-ubuntu-22.04.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-ubuntu-22.04.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-ubuntu-22.04.zip"
    ],
)

http_file(
    name = "firefox-ubuntu20.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-ubuntu-20.04-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-ubuntu-20.04-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-ubuntu-20.04-arm64.zip"
    ],
)

http_file(
    name = "firefox-ubuntu22.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-ubuntu-22.04-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-ubuntu-22.04-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-ubuntu-22.04-arm64.zip"
    ],
)

http_file(
    name = "firefox-debian11-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-debian-11.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-debian-11.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-debian-11.zip"
    ],
)

http_file(
    name = "firefox-debian11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-debian-11-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-debian-11-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-debian-11-arm64.zip"
    ],
)

http_file(
    name = "firefox-debian12-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-debian-12.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-debian-12.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-debian-12.zip"
    ],
)

http_file(
    name = "firefox-debian12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-debian-12-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-debian-12-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-debian-12-arm64.zip"
    ],
)

http_file(
    name = "firefox-mac10.13",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac10.14",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac10.15",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac11",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-mac12",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-mac13",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac13-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-mac14",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13.zip"
    ],
)

http_file(
    name = "firefox-mac14-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-win64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox/1447/firefox-win64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox/1447/firefox-win64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox/1447/firefox-win64.zip"
    ],
)

http_file(
    name = "firefox-beta-ubuntu20.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-20.04.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-20.04.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-20.04.zip"
    ],
)

http_file(
    name = "firefox-beta-ubuntu22.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-22.04.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-22.04.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-22.04.zip"
    ],
)

http_file(
    name = "firefox-beta-ubuntu22.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-22.04-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-22.04-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-ubuntu-22.04-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-debian11-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-11.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-11.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-11.zip"
    ],
)

http_file(
    name = "firefox-beta-debian11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-11-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-11-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-11-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-debian12-x64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-12.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-12.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-12.zip"
    ],
)

http_file(
    name = "firefox-beta-debian12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-12-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-12-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-debian-12-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-mac10.13",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac10.14",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac10.15",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac11",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-mac12",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-mac13",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac13-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-mac14",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13.zip"
    ],
)

http_file(
    name = "firefox-beta-mac14-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-mac-13-arm64.zip"
    ],
)

http_file(
    name = "firefox-beta-win64",
    urls = [
        "https://playwright.azureedge.net/builds/firefox-beta/1447/firefox-beta-win64.zip",
        "https://playwright-akamai.azureedge.net/builds/firefox-beta/1447/firefox-beta-win64.zip",
        "https://playwright-verizon.azureedge.net/builds/firefox-beta/1447/firefox-beta-win64.zip"
    ],
)

http_file(
    name = "webkit-ubuntu20.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-ubuntu-20.04.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-ubuntu-20.04.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-ubuntu-20.04.zip"
    ],
)

http_file(
    name = "webkit-ubuntu22.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-ubuntu-22.04.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-ubuntu-22.04.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-ubuntu-22.04.zip"
    ],
)

http_file(
    name = "webkit-ubuntu20.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-ubuntu-20.04-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-ubuntu-20.04-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-ubuntu-20.04-arm64.zip"
    ],
)

http_file(
    name = "webkit-ubuntu22.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-ubuntu-22.04-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-ubuntu-22.04-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-ubuntu-22.04-arm64.zip"
    ],
)

http_file(
    name = "webkit-debian11-x64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-debian-11.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-debian-11.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-debian-11.zip"
    ],
)

http_file(
    name = "webkit-debian11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-debian-11-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-debian-11-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-debian-11-arm64.zip"
    ],
)

http_file(
    name = "webkit-debian12-x64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-debian-12.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-debian-12.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-debian-12.zip"
    ],
)

http_file(
    name = "webkit-debian12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-debian-12-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-debian-12-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-debian-12-arm64.zip"
    ],
)

http_file(
    name = "webkit-mac10.14",
    urls = [
        "https://playwright.azureedge.net/builds/deprecated-webkit-mac-10.14/1992/deprecated-webkit-mac-10.14.zip",
        "https://playwright-akamai.azureedge.net/builds/deprecated-webkit-mac-10.14/1992/deprecated-webkit-mac-10.14.zip",
        "https://playwright-verizon.azureedge.net/builds/deprecated-webkit-mac-10.14/1992/deprecated-webkit-mac-10.14.zip"
    ],
)

http_file(
    name = "webkit-mac10.15",
    urls = [
        "https://playwright.azureedge.net/builds/deprecated-webkit-mac-10.15/1992/deprecated-webkit-mac-10.15.zip",
        "https://playwright-akamai.azureedge.net/builds/deprecated-webkit-mac-10.15/1992/deprecated-webkit-mac-10.15.zip",
        "https://playwright-verizon.azureedge.net/builds/deprecated-webkit-mac-10.15/1992/deprecated-webkit-mac-10.15.zip"
    ],
)

http_file(
    name = "webkit-mac11",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-11.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-11.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-11.zip"
    ],
)

http_file(
    name = "webkit-mac11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-11-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-11-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-11-arm64.zip"
    ],
)

http_file(
    name = "webkit-mac12",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-12.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-12.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-12.zip"
    ],
)

http_file(
    name = "webkit-mac12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-12-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-12-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-12-arm64.zip"
    ],
)

http_file(
    name = "webkit-mac13",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-13.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-13.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-13.zip"
    ],
)

http_file(
    name = "webkit-mac13-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-13-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-13-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-13-arm64.zip"
    ],
)

http_file(
    name = "webkit-mac14",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-14.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-14.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-14.zip"
    ],
)

http_file(
    name = "webkit-mac14-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-mac-14-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-mac-14-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-mac-14-arm64.zip"
    ],
)

http_file(
    name = "webkit-win64",
    urls = [
        "https://playwright.azureedge.net/builds/webkit/1992/webkit-win64.zip",
        "https://playwright-akamai.azureedge.net/builds/webkit/1992/webkit-win64.zip",
        "https://playwright-verizon.azureedge.net/builds/webkit/1992/webkit-win64.zip"
    ],
)

http_file(
    name = "ffmpeg-ubuntu20.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip"
    ],
)

http_file(
    name = "ffmpeg-ubuntu22.04-x64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip"
    ],
)

http_file(
    name = "ffmpeg-ubuntu20.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-ubuntu22.04-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-debian11-x64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip"
    ],
)

http_file(
    name = "ffmpeg-debian11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-debian12-x64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip"
    ],
)

http_file(
    name = "ffmpeg-debian12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-mac10.13",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac10.14",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac10.15",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac11",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac11-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-mac12",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac12-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-mac13",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac13-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-mac14",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac.zip"
    ],
)

http_file(
    name = "ffmpeg-mac14-arm64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip"
    ],
)

http_file(
    name = "ffmpeg-win64",
    urls = [
        "https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-win64.zip",
        "https://playwright-akamai.azureedge.net/builds/ffmpeg/1009/ffmpeg-win64.zip",
        "https://playwright-verizon.azureedge.net/builds/ffmpeg/1009/ffmpeg-win64.zip"
    ],
)